<a href="https://colab.research.google.com/github/AsharZafar/Python/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np

In [3]:


#create a 2D array

a=np.array([[1,2],[3,5],[6,9]])
a.size
a.shape
a

array([[1, 2],
       [3, 5],
       [6, 9]])

In [ ]:
b=np.array([[1,2],[3,5],[6,9]],dtype=complex)
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 5.+0.j],
       [6.+0.j, 9.+0.j]])

In [ ]:
z=np.zeros((3,4))
z
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(0,5)

#for steps we use
#. np.arange(0,5,2)
#

array([0, 1, 2, 3, 4])

In [ ]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
reshaped=a.reshape(6,1)

In [ ]:

#ravel converts a 2d array into 1d array
ravel=np.ravel(reshaped)
ravel

array([1, 2, 3, 5, 6, 9])

In [ ]:
a.min()
a.max()
a.sum()
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.23606798],
       [2.44948974, 3.        ]])

In [20]:
a=np.array([[1,5],[1,6],[2,5],[3,4],[6,2]])
#a[Row,column]
a[3,1] # means 4 th row 2nd column

4

In [ ]:
a[0:2,1] #0 to 1st row and 2nd column

array([5, 6])

In [4]:
a

array([[1, 2],
       [3, 5],
       [6, 9]])

In [6]:
for row in a:
    print (row)

[1 2]
[3 5]
[6 9]


In [8]:
for cell in a.flat:
    print(cell)

1
2
3
5
6
9


In [10]:
b=np.array([[6,5],[3,4],[9,8]])

In [16]:

#or
b=np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
np.vstack((a,b))

array([[1, 2],
       [3, 5],
       [6, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [19]:
np.hstack((a,b))

array([[1, 2, 0, 1],
       [3, 5, 2, 3],
       [6, 9, 4, 5]])

In [ ]:
#sPlitting into 3 diffrent arrays

In [22]:
c=np.arange(30). reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
Result=np.hsplit(c,3)
Result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [28]:
X=np.arange(12). reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
Z=X>4
Z

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
X[Z]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
#this can also be use to replace the numbers example

In [34]:
X[Z]=-1
X

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [41]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
#nd iter

for x in np.nditer(a,order='C'):
    print(x)

# to change the order or print it in
#coluknnwise just replace it C with F

0
1
2
3
4
5
6
7
8
9
10
11
